sudo: false

language: go

go:
  - 1.4.2

install:
  - go get -t -v -d ./...
  - go build -v
  - go install github.com/onsi/ginkgo/ginkgo

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - go tool vet -composites=false $(ls -d */ | grep -v Godeps)
  - go vet -composites=false github.com/mfine30/prodda
  - ginkgo -p -r -race -failOnPending -randomizeAllSpecs

branches:
  only:
    - master
    - develop

