sudo: false

language: go

go:
  - 1.4.2

install:
  - go get -t -v -d ./...
  - go build -v

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - ./scripts/ci/test-unit
  - ./scripts/ci/test-integration

branches:
  only:
    - master
    - develop

